### ISSUE TITLE
Making an RoR2 mod help

### ISSUE THREAD

**Issue by i-dk737** [HippoInAFedora/RifterMod#1]
Hello Hippo,
I just saw your mod on Thunderstore, and thought you could help with my question.
I been wanting to make an RoR2 mod for the longest time, but I'm not understanding the few pieces of documentation that are present. Would it be possible for you to walk me through how you are making your mod?
Information like how you set up the base Henry file in Unity to ho you get your assets, to how you make custom attacks would be a great help. Any and all tips you can give me would be amazing.

**Comment by HippoInAFedora** [comment]
Hey!
I'd be happy to help, but I think the best idea is to join the Risk of Rain 2 Modding discord. There are plenty of people ready to help there, and can assist way more than I can. I can also help when I can there too
